module.exports = {
    registerUser: require('./register-user'),
    authenticateUser: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    updateUser: require('./update-user'),
    retrieveSong: require('./retrieve-song'),
    retrieveAlbum: require('./retrieve-album'),
    retrieveGenre: require('./retrieve-genre'),
    retrieveYear: require('./retrieve-year'),
    retrieveSearch: require('./retrieve-search'),
    retrieveArtist: require('./retrieve-artist'),
    retrieveSongName: require('./retrieve-song-name'),
    updateChart: require('./update-chart'),
    retrieveChart: require('./retrieve-chart'),
    buyProducts: require('./buy-products'),
    updatePlaylist: require('./update-playlist'),
    retrievePlaylist: require('./retrieve-playlist'),
    retrieveBestSellings: require('./retrieve-best-sellings'),
    saveCreditCard: require('./save-credit-card'),
    retrieveCreditCards: require('./retrieve-credit-card'),
    retrieveOneCreditCard: require('./retrieve-one-credit-card'),
    retrieveMostPlayedSongs: require('./retrieve-most-played-songs'),
    retrieveMostPlayedArtists: require('./retrieve-most-played-artists'),
    saveShippingInfo: require('./save-shipping-info'),
    retrieveShippingInformation: require('./retrieve-shipping-information'),
    retrieveOneShipping: require('./retrieve-one-shipping'),
    retrievePortrait: require('./retrieve-portrait')
}